CREATE DATABASE miningdb;
USE miningdb;

CREATE TABLE usuario (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
nickname VARCHAR(50) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL
);

SELECT * FROM usuario;